- name: Install and manage Nexus Repository
  docker_container:
    name: nexus
    image: sonatype/nexus3
    state: started
    pull: false
    volumes:
    - "/srv/nexus-data:/nexus-data"
    ports:
    - "8081:8081"
