- name: Install and manage gitlab-runner
  docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    state: started
    pull: true

    volumes:
    - "/srv/gitlab-runner/config:/etc/gitlab-runner"
    - "/var/run/docker.sock:/var/run/docker.sock"
